### PR TITLE
Correcting name conflict between custom class in /lib/date-utils.dart…

### PR DESCRIPTION
**Pull request by plinkos**
Correcting name conflict between custom class in /lib/date-utils.dart and package:flutter/src/material/date.dart

### CODE REVIEW

**Comment by plinkos** [comment]
Fix for issue #35

**Comment by eripe970** [comment]
Can this be merged?

**Comment by plinkos** [comment]
Yes, please. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by IronLad85** [comment]
> Can this be merged?
@eripe970 
@plinkos 
Sorry I was Inactive to take a look at the pull requests and issues. I am merging this now.

**Comment by eripe970** [comment]
👍

**Pull request merged**
